### ISSUE TITLE
web support..?

### ISSUE THREAD

**Issue by riloraspopo** [i-Naji/tdlib#24]
any information about this lib for flutter web..?

**Comment by i-Naji** [comment]
I think tdlib does not support flutter web (No Plans Yet!")

**Comment by halkliff** [comment]
It indeed does not, since the TDLib baked in here is the mobile version of it (And not even support for iOS, but I'm not complaining).
In fact, we'd need to do the same work with the web libs used by the web Telegram, and even so I'm not sure if we'd have compatibility with all functions and objects...

**Comment by PaulVipond** [comment]
Is there any way of working with Tdlib with Flutter and iOS?

**Comment by i-Naji** [comment]
supported with extra steps
